const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE:'CHANGE_LANGUAGE',
    
    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    SET_USER_ROLE:'SET_USER_ROLE',

    //admin

    //product
    INCREASE_ITEM_WHITELIST:'INCREASE_ITEM_WHITELIST',
    DECREASE_ITEM_WHITELIST:'DECREASE_ITEM_WHITELIST',
    INCREASE_ITEM_CARTLIST:'INCREASE_ITEM_CARTLIST',
    DECREASE_ITEM_CARTLIST:'DECREASE_ITEM_CARTLIST',
    
    GET_PRODUCT_SUCCESS:'GET_PRODUCT_SUCCESS',
    GET_PRODUCT_FAILED:'GET_PRODUCT_FAILED',

    //bill
    GET_ORDER_SUCCESS:'GET_ORDER_SUCCESS',
    GET_ORDER_FAILED:'GET_ORDER_FAILED',
    GET_BILL_SUCCESS:'GET_BILL_SUCCESS',
    GET_BILL_FAILED:'GET_BILL_FAILED',
})

export default actionTypes;